# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ik0gVhBibTgfdiEFhIUyisloEKYjB2hE
"""

import random

def sonni_top():
    print("Xush kelibsiz! Men 1 dan 100 gacha bo'lgan bir sonni o'yladim. Topishga harakat qiling!")

    tasodifiy_son = random.randint(1, 100)
    taxminlar = 0

    while True:
        try:
            foydalanuvchi_soni = int(input("Son kiriting: "))
            taxminlar += 1

            if foydalanuvchi_soni < tasodifiy_son:
                print("Kattaroq son o'ylang!")
            elif foydalanuvchi_soni > tasodifiy_son:
                print("Kichikroq son o'ylang!")
            else:
                print(f"Tabriklaymiz! {taxminlar} ta urinishda to'g'ri topdingiz.")
                break
        except ValueError:
            print("Iltimos, butun son kiriting!")

if __name__ == "__main__":
    sonni_top()